version: "3.7"
services:
  app:
    build:
      args:
        user: fulljaus
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: market
    container_name: market-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - market

  db:
    image: mysql:5.7
    container_name: market-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: fj-market-demo
      MYSQL_ROOT_PASSWORD: XSslm_4n3vR
      MYSQL_PASSWORD: XSslm_4n3vU
      MYSQL_USER: admin
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - market

  nginx:
    image: nginx:alpine
    container_name: market-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - market

networks:
  market:
    driver: bridge
